name: Push dhis2_tracker_extract

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/push_dhis2_tracker_extract.yaml"
      - "dhis2_tracker_extract/**"
      - "!dhis2_tracker_extract/docs/**"
      - "!dhis2_tracker_extract/README.md"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Configure OpenHEXA CLI
        uses: blsq/openhexa-cli-action@v1
        with:
          workspace: "drc-cousp-e26493"
          token: ${{ secrets.OH_TOKEN }}

      - name: Push pipeline to OpenHEXA
        env:
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          COMMIT_SHA: ${{ github.sha }}
        run: |
          openhexa pipelines push dhis2_tracker_extract \
            --code "dhis2-extract-events" \
            --description "${COMMIT_MESSAGE}" \
            --link "https://github.com/BLSQ/openhexa-pipelines-drc-cousp/commit/${COMMIT_SHA}" \
            --yes
